# Generated by Django 4.2.21 on 2025-05-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(choices=[('bantu', 'Bantu'), ('nilotic', 'Nilotic'), ('cushitic', 'Cushitic'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('contributors_count', models.PositiveIntegerField(default=0)),
                ('words_count', models.PositiveIntegerField(default=0)),
                ('sentences_count', models.PositiveIntegerField(default=0)),
                ('audio_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
